/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface ArModal {
      'close': () => void;
      'modalTitle': string;
      'open': () => void;
    }
  }

  interface HTMLArModalElement extends StencilComponents.ArModal, HTMLStencilElement {}

  var HTMLArModalElement: {
    prototype: HTMLArModalElement;
    new (): HTMLArModalElement;
  };
  interface HTMLElementTagNameMap {
    'ar-modal': HTMLArModalElement;
  }
  interface ElementTagNameMap {
    'ar-modal': HTMLArModalElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'ar-modal': JSXElements.ArModalAttributes;
    }
  }
  namespace JSXElements {
    export interface ArModalAttributes extends HTMLAttributes {
      'modalTitle'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ArTab {
      'close': () => void;
      'open': () => void;
      'tabTitle': string;
    }
  }

  interface HTMLArTabElement extends StencilComponents.ArTab, HTMLStencilElement {}

  var HTMLArTabElement: {
    prototype: HTMLArTabElement;
    new (): HTMLArTabElement;
  };
  interface HTMLElementTagNameMap {
    'ar-tab': HTMLArTabElement;
  }
  interface ElementTagNameMap {
    'ar-tab': HTMLArTabElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'ar-tab': JSXElements.ArTabAttributes;
    }
  }
  namespace JSXElements {
    export interface ArTabAttributes extends HTMLAttributes {
      'tabTitle'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;